services:
  redis:
    image: redis:latest
    env_file:
      - .env
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"  # bind to localhost only
    command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3